environments:
  local:
    values:
      - kubeContext: default
      - installed:
          prometheus: true
          chartmuseum: false
          whoamiMn: false
          surfScreenshotter: false
      - version:
          prometheus: 9.3.2
          chartmuseum: 0
          whoamiMn: 0
          surfScreenshotter: 0
  dev:
    values:
      - kubeContext: nuc
      - installed:
          prometheus: false
          chartmuseum: false
          whoamiMn: false
          surfScreenshotter: false
      - version:
          prometheus: 0
          chartmuseum: 0
          whoamiMn: 0
          surfScreenshotter: 0
  test:
    values:
      - kubeContext: nuc
      - installed:
          prometheus: false
          chartmuseum: false
          whoamiMn: true
          surfScreenshotter: false
      - version:
          prometheus: 0
          chartmuseum: 0
          whoamiMn: 0.6.0
          surfScreenshotter: 0
  prod:
    values:
      - kubeContext: nuc
      - installed:
          prometheus: true
          chartmuseum: true
          whoamiMn: true
          surfScreenshotter: true
      - version:
          prometheus: 9.3.2
          chartmuseum: 2.13.3
          whoamiMn: 0.6.0
          surfScreenshotter: 0.3.0

releases:
  - name: surf-screenshotter
    namespace: surf-screenshotter-{{ .Environment.Name }}
    chart: tons/surf-screenshotter
    version: {{ .Values.version.surfScreenshotter }}
    installed: {{ .Values.installed.surfScreenshotter }}
    kubeContext: {{ .Values.kubeContext }}

  - name: whoami-mn
    namespace: whoami-mn-{{ .Environment.Name }}
    chart: tons/whoami-mn
    version: {{ .Values.version.whoamiMn }}
    installed: {{ .Values.installed.whoamiMn }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - environments/{{ .Environment.Name }}/whoami-mn-values.yaml

  - name: prometheus
    namespace: prometheus
# https://github.com/helm/charts/issues/21690
#    chart: prometheus-community/kube-prometheus-stack
#    version: 9.4.3
    chart: stable/prometheus-operator
    version: {{ .Values.version.prometheus }}
    installed: {{ .Values.installed.prometheus }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - environments/{{ .Environment.Name }}/prometheus-values.gotmpl

  - name: chartmuseum
    namespace: chartmuseum
    chart: stable/chartmuseum
    version: {{ .Values.version.chartmuseum }}
    installed: {{ .Values.installed.chartmuseum }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - environments/{{ .Environment.Name }}/chartmuseum-values.gotmpl

repositories:
#  - name: prometheus-community
#    url: https://prometheus-community.github.io/helm-charts
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: tons
    url: https://helm-charts.fitfit.dk
    username: {{ requiredEnv "CHARTMUSEUM_AUTH_USER" }}
    password: {{ requiredEnv "CHARTMUSEUM_AUTH_PASS" }}
