environments:
  local:
    values:
      - kubeContext: default
      - installed:
          prometheus: true
          chartmuseum: false
      - version:
          prometheus: 9.3.2
          chartmuseum: 0
  dev:
    values:
      - kubeContext: nuc
      - installed:
          prometheus: false
          chartmuseum: false
      - version:
          prometheus: 0
          chartmuseum: 0
  test:
    values:
      - kubeContext: nuc
      - installed:
          prometheus: false
          chartmuseum: false
      - version:
          prometheus: 0
          chartmuseum: 0
  prod:
    values:
      - kubeContext: nuc
      - installed:
          prometheus: true
          chartmuseum: true
      - version:
          prometheus: 9.3.2
          chartmuseum: 2.13.3

releases:
  - name: prometheus
    namespace: prometheus
# https://github.com/helm/charts/issues/21690
#    chart: prometheus-community/kube-prometheus-stack
#    version: 9.4.3
    chart: stable/prometheus-operator
    version: {{ .Values.version.prometheus }}
    installed: {{ .Values.installed.prometheus }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - environments/{{ .Environment.Name }}/prometheus-values.gotmpl

  - name: chartmuseum
    namespace: chartmuseum
    chart: stable/chartmuseum
    version: {{ .Values.version.chartmuseum }}
    installed: {{ .Values.installed.chartmuseum }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - environments/{{ .Environment.Name }}/chartmuseum-values.gotmpl

repositories:
#  - name: prometheus-community
#    url: https://prometheus-community.github.io/helm-charts
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
