releases:
  - name: prometheus
    namespace: prometheus
# https://github.com/helm/charts/issues/21690
#    chart: prometheus-community/kube-prometheus-stack
#    version: 9.4.3
    chart: stable/prometheus-operator
    version: 9.3.2
    values:
      - grafana:
          adminPassword: {{ requiredEnv "GRAFANA_ADMIN_PASSWORD" }}
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - grafana.fitfit.dk
            path: /
            tls:
              - secretName: prometheus-tls
                hosts:
                  - grafana.fitfit.dk

  - name: chartmuseum
    namespace: chartmuseum
    chart: stable/chartmuseum
    version: 2.13.3
    values:
      - ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - name: helm-charts.fitfit.dk
              path: /
              tls: true
              tlsSecret: chartmuseum-tls
      - env:
          open:
            DISABLE_API: false
            STORAGE: local
          secret:
            BASIC_AUTH_USER: {{ requiredEnv "CHARTMUSEUM_AUTH_USER" }}
            BASIC_AUTH_PASS: {{ requiredEnv "CHARTMUSEUM_AUTH_PASS" }}
      - persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 100M

repositories:
#  - name: prometheus-community
#    url: https://prometheus-community.github.io/helm-charts
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

