environments:
  local:
    values:
      - kubeContext: default
      - surfEasyEdit:
          installed: true
          version: 1.0.0
      - surfEasyEditDatabase:
          installed: true
          version: 10.1.1
      - autoYoutubeDl:
          installed: false
          version: 0
      - surfScreenshotter:
          installed: false
          version: 0
      - surfAisScreenshot:
          installed: false
          version: 0
      - whoamiMn:
          installed: false
          version: 0
      - chartmuseum:
          installed: false
          version: 0
      - prometheus:
          installed: true
          version: 9.3.2
  dev:
    values:
      - kubeContext: nuc
      - kubewatcher:
          installed: false
          version: 0
      - surfEasyEdit:
          installed: false
          version: 0
      - surfEasyEditDatabase:
          installed: false
          version: 0
      - autoYoutubeDl:
          installed: false
          version: 0
      - surfScreenshotter:
          installed: false
          version: 0
      - surfAisScreenshot:
          installed: false
          version: 0
      - whoamiMn:
          installed: true
          version: 0.7.0
      - chartmuseum:
          installed: false
          version: 0
      - prometheus:
          installed: false
          version: 0
  test:
    values:
      - kubeContext: nuc
      - kubewatcher:
          installed: false
          version: 0
      - surfEasyEdit:
          installed: false
          version: 0
      - surfEasyEditDatabase:
          installed: false
          version: 0
      - autoYoutubeDl:
          installed: false
          version: 0
      - surfScreenshotter:
          installed: false
          version: 0
      - surfAisScreenshot:
          installed: false
          version: 0
      - whoamiMn:
          installed: true
          version: 0.7.0
      - chartmuseum:
          installed: false
          version: 0
      - prometheus:
          installed: false
          version: 0
  prod:
    values:
      - kubeContext: nuc
      - kubewatcher:
          installed: true
          version: 1.2.0
      - surfEasyEdit:
          installed: true
          version: 1.3.0
      - surfEasyEditDatabase:
          installed: true
          version: 10.1.1
      - autoYoutubeDl:
          installed: true
          version: 1.0.0
      - surfScreenshotter:
          installed: true
          version: 0.8.0
      - surfAisScreenshot:
          installed: true
          version: 1.1.0
      - whoamiMn:
          installed: true
          version: 0.7.0
      - chartmuseum:
          installed: true
          version: 2.13.3
      - prometheus:
          installed: false
          version: 9.3.2

releases:
  - name: kubewatcher
    namespace: kubewatcher
    chart: tons/kubewatcher
    verify: true
    version: {{ .Values.kubewatcher.version }}
    installed: {{ .Values.kubewatcher.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/kubewatcher-values.gotmpl

  - name: surf-easy-edit
    namespace: surf-easy-edit-{{ .Environment.Name }}
    chart: tons/surf-easy-edit
    verify: true
    version: {{ .Values.surfEasyEdit.version }}
    installed: {{ .Values.surfEasyEdit.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/surf-easy-edit-values.gotmpl

  - name: surf-easy-edit-database
    namespace: surf-easy-edit-{{ .Environment.Name }}
    chart: bitnami/postgresql
    verify: false
    version: {{ .Values.surfEasyEditDatabase.version }}
    installed: {{ .Values.surfEasyEditDatabase.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/surf-easy-edit-database-values.gotmpl

  - name: auto-youtube-dl
    namespace: auto-youtube-dl
    chart: tons/auto-youtube-dl
    version: {{ .Values.autoYoutubeDl.version }}
    installed: {{ .Values.autoYoutubeDl.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/auto-youtube-dl-values.yaml

  - name: surf-ais-screenshot
    namespace: surf-ais-screenshot-{{ .Environment.Name }}
    chart: tons/surf-ais-screenshot
    verify: true
    version: {{ .Values.surfAisScreenshot.version }}
    installed: {{ .Values.surfAisScreenshot.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/surf-ais-screenshot-values.gotmpl

  - name: surf-screenshotter
    namespace: surf-screenshotter-{{ .Environment.Name }}
    chart: tons/surf-screenshotter
    verify: true
    version: {{ .Values.surfScreenshotter.version }}
    installed: {{ .Values.surfScreenshotter.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/surf-screenshotter-values.yaml

  - name: whoami-mn
    namespace: whoami-mn-{{ .Environment.Name }}
    chart: tons/whoami-mn
    verify: true
    version: {{ .Values.whoamiMn.version }}
    installed: {{ .Values.whoamiMn.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/whoami-mn-values.yaml

  - name: prometheus
    namespace: prometheus
# https://github.com/helm/charts/issues/21690
#    chart: prometheus-community/kube-prometheus-stack
#    version: 9.4.3
    chart: stable/prometheus-operator
    version: {{ .Values.prometheus.version }}
    installed: {{ .Values.prometheus.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/prometheus-values.gotmpl

  - name: chartmuseum
    namespace: chartmuseum
    chart: stable/chartmuseum
    version: {{ .Values.chartmuseum.version }}
    installed: {{ .Values.chartmuseum.installed }}
    kubeContext: {{ .Values.kubeContext }}
    values:
      - values/{{ .Environment.Name }}/chartmuseum-values.gotmpl

repositories:
#  - name: prometheus-community
#    url: https://prometheus-community.github.io/helm-charts
  - name: stable
    url: https://charts.helm.sh/stable
  - name: tons
    url: https://helm-charts.fitfit.dk
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
